kind: PersistentVolume
apiVersion: v1
metadata:
  name: kaa.pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "medium"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/lib/data"
