---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: persistence
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: clients
  selector:
    app: mariadb
    tier: persistence
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        tier: persistence
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.1.22
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          tcpSocket:
            port: clients-port
          initialDelaySeconds: 150
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: clients-port
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          requests:
            memory: 100Mi
        volumeMounts:
        - name: data-storage-volume
          mountPath: "/var/lib/mysql"
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MYSQL_ROOT_PASSWORD
          value: kaa-secret-pw
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb.credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb.credentials
              key: password
        - name: MYSQL_DATABASE
          value: cm_service
        ports:
        - name: clients-port
          containerPort: 3306
      volumes:
      - name: data-storage-volume
        persistentVolumeClaim:
          claimName: mariadb-claim
