kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "medium"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
