kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-epr-data-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "mongo-epr-pv"
spec:
  capacity:
    storage: 100Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/lib/mongo-epr-data"
