#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: security.passwords
#type: Opaque
#data:
#  keyStorePassword: a2V5X3N0b3JlX3Bhc3M=
#  keyPassword: a2V5X3Bhc3M=
#  trustStorePassword: dHJ1c3Rfc3RvcmVfcGFzcw==
---
apiVersion: v1
kind: Service
metadata:
  name: kpc-service
  labels:
    app: kpc-service
    tier: backend
spec:
  type: "LoadBalancer"
  ports:
    # the port that this service should serve on
  - port: 1883
    targetPort: 1883
    nodePort: 30720
    name: mqtt
  selector:
    app: kpc-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kpc-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kpc-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: hub-deploy
      containers:
      - name: kpc-service
        image: hub.kaaiot.io/kaaiot/kpc/kpc-service:1.0.0-SNAPSHOT
        terminationMessagePolicy: FallbackToLogsOnError
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: health-port
          initialDelaySeconds: 150
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: health-port
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
          - mountPath: /usr/lib/kpc-service/conf
            name: kpc-conf-volume
#          - mountPath: /usr/lib/kpc-service/security/keyStore
#            name: key-store-volume
#            readOnly: true
#          - mountPath: /usr/lib/kpc-service/security/trustStore
#            name: trust-store-volume
#            readOnly: true
#          - mountPath: /usr/lib/kpc-service/security/passwords
#            name: passwords-volume
#            readOnly: true
        resources:
          requests:
            memory: 350Mi
          limits:
            memory: 1800Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: CREDENTIAL_HOST_PORT
          value: http://cm-service.default.svc.cluster.local:30730
        - name: CM_INSTANCE_NAME
          value: cm
        - name: NATS_HOST_PORT
          value: nats://nats-service.default.svc.cluster.local:4222
        - name: DEPENDENCY_SERVICES_WAIT_TIMEOUT_SEC
          value: "60"    # -1 means unlimited timeout
        - name: JAVA_OPTIONS
          value: -Xmx1500m
        - name: INSTANCE_NAME
          value: kpc
        - name: CLIENT_ENABLE_AUTH
          value: "false"
        - name: CERTIFICATE_CM_VALIDATION
          value: "false"
        - name: CONFIG_REPOSITORY_SERVICE_URL
          value: "http://scr-service.default.svc.cluster.local:30770"
          # Point to the location of configuration for transport protocols such as MQTT or CoAP.
          # If variable is not specified or value is empty, the service will get default configurations in application-<protocol-name>.yml file.
        - name: APP_CONFIG_PATH
          value: /usr/lib/kpc-service/conf/service-config.yml
        - name: JMX_PORT
          value: "30722"
        - name: JMX_MONITOR_USER_PASSWORD
          value: monitor
        ports:
        - name: transport-port
          containerPort: 1883
        - name: health-port
          containerPort: 30721
        - name: jmx-port
          containerPort: 30722
      volumes:
        - name: kpc-conf-volume
          hostPath:
            path: /usr/lib/kpc-service/conf
#        - name: trust-store-volume
#          hostPath:
#            path: /usr/lib/kpc-service/trustStore
#        - name: key-store-volume
#          secret:
#            secretName: mqtt.server.keystore
#        - name: passwords-volume
#          secret:
#            secretName: security.passwords