---
apiVersion: v1
kind: Service
metadata:
  name: ecr-service
  labels:
    app: ecr-service
    tier: backend
spec:
  type: "LoadBalancer"
  ports:
  - port: 30760
    targetPort: 30760
    nodePort: 30760
    name: ecr
  selector:
    app: ecr-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ecr-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecr-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: hub-deploy
      containers:
      - name: ecr-service
        image: hub.kaaiot.io/kaaiot/ecr/ecr-service:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /health
            port: ecr-port
          initialDelaySeconds: 250
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: ecr-port
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
          - mountPath: /usr/lib/ecr-service/conf
            name: ecr-conf-volume
        resources:
          requests:
            memory: 350Mi
          limits:
            memory: 1Gi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: INSTANCE_NAME
          value: ecr
        - name: NATS_HOST_PORT
          value: nats://nats-service.default.svc.cluster.local:4222
        - name: CASSANDRA_HOST_PORT
          value: cassandra.default.svc.cluster.local:9042
        - name: DEPENDENCY_SERVICES_WAIT_TIMEOUT_SEC
          value: "120"
        - name: JAVA_OPTIONS
          value: -Xmx700m
        - name: EPR_HOST_PORT
          value: http://epr-service.default.svc.cluster.local:30750
        - name: EPR_INSTANCE_NAME
          value: epr
        - name: JMX_PORT
          value: "30761"
        - name: JMX_MONITOR_USER_PASSWORD
          value: monitor
        - name: APP_CONFIG_PATH
          value: /usr/lib/ecr-service/conf/app/app-config.yml
        - name: CONFIG_REPOSITORY_SERVICE_URL
          value: "http://scr-service.default.svc.cluster.local:30770"
        ports:
        - name: ecr-port
          containerPort: 30760
        - name: jmx-port
          containerPort: 30761
      volumes:
        - name: ecr-conf-volume
          hostPath:
            path: /usr/lib/ecr-service/conf

