---
apiVersion: v1
kind: Service
metadata:
  name: wsts-service
  labels:
    app: wsts-service
    tier: backend
spec:
  type: "LoadBalancer"
  ports:
  - port: 30930
    targetPort: 30930
    nodePort: 30930
    name: wsts
  selector:
    app: wsts-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wsts-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wsts-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: hub-deploy
      containers:
      - name: wsts-service
        image: hub.kaaiot.io/kaaiot/wsts/wsts-service:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /health
            port: wsts-port
          initialDelaySeconds: 150
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: wsts-port
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
          - mountPath: /usr/lib/wsts-service/conf
            name: wsts-conf-volume
        resources:
          requests:
            memory: 350Mi
          limits:
            memory: 1Gi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: INSTANCE_NAME
          value: wsts
        - name: EPTS_INSTANCE_NAME
          value: epts
        - name: NATS_HOST_PORT
          value: nats://nats-service.default.svc.cluster.local:4222
        - name: DEPENDENCY_SERVICES_WAIT_TIMEOUT_SEC
          value: "120"
        - name: JAVA_OPTIONS
          value: -Xmx700m
        - name: CONFIG_REPOSITORY_SERVICE_URL
          value: "http://scr-service.default.svc.cluster.local:30770"
        - name: JMX_PORT
          value: "30931"
        - name: JMX_MONITOR_USER_PASSWORD
          value: monitor
        - name: APP_CONFIG_PATH
          value: /usr/lib/wsts-service/conf/app/app-config.yml
        ports:
        - name: wsts-port
          containerPort: 30930
        - name: jmx-port
          containerPort: 30931
      volumes:
        - name: wsts-conf-volume
          hostPath:
            path: /usr/lib/wsts-service/conf
