---
apiVersion: v1
kind: Service
metadata:
  name: gizmo-service
  labels:
    app: gizmo-service
    tier: backend
spec:
  type: "LoadBalancer"
  ports:
  - port: 32702
    targetPort: 32702
    nodePort: 32702
    name: gizmo
  selector:
    app: gizmo-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gizmo-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gizmo-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: hub-deploy
      containers:
      - name: gizmo-service
        image: hub.kaaiot.io/evangelism/solutions/gizmo/simulators/gizmo/gizmo-service:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /health
            port: gizmo-port
          initialDelaySeconds: 150
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: gizmo-port
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          requests:
            memory: 350Mi
          limits:
            memory: 1Gi
        envFrom:
        - configMapRef:
            name: general-services-config
        env:
        - name: INSTANCE_NAME
          value: gizmo
        - name: DEPENDENCY_SERVICES_WAIT_TIMEOUT_SEC
          value: "60"
        - name: JAVA_OPTIONS
          value: -Xmx700m
        - name: KPC_HOST_PORT
          value: tcp://kpc-service.default.svc.cluster.local:1883
        - name: ECR_HOST_PORT
          value: http://ecr-service.default.svc.cluster.local:30760
        - name: CMX_HOST_PORT
          value: http://cmx-service.default.svc.cluster.local:30790
        - name: CONFIG_REPOSITORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: scr-url-config
              key: scr-url
        ports:
        - name: gizmo-port
          containerPort: 32702
---
