---
apiVersion: v1
kind: Service
metadata:
  name: epts-service
  labels:
    app: epts-service
    tier: backend
spec:
  type: "LoadBalancer"
  ports:
  - port: 30740
    targetPort: 30740
    nodePort: 30740
    name: epts
  - port: 30742
    targetPort: 30742
    nodePort: 30742
    name: debug
  selector:
    app: epts-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: epts-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: epts-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: hub-deploy
      containers:
      - name: epts-service
        image: hub.kaaiot.io/kaaiot/epts/epts-service:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - mountPath: /usr/lib/epts-service/conf
            name: epts-conf-volume
        resources:
          requests:
            memory: 350Mi
          limits:
            memory: 1Gi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: NATS_HOST_PORT
          value: nats://nats-service.default.svc.cluster.local:4222
        - name: INSTANCE_NAME
          value: epts
        - name: CASSANDRA_HOST_PORT
          value: cassandra.default.svc.cluster.local:9042
        - name: DEPENDENCY_SERVICES_WAIT_TIMEOUT_SEC
          value: "120"
        - name: APP_CONFIG_PATH
          value: /usr/lib/epts-service/conf/app/app-config.yml
        - name: JAVA_OPTIONS
          value: -Xmx700m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=30742
        - name: JMX_PORT
          value: "30741"
        - name: JMX_MONITOR_USER_PASSWORD
          value: monitor
        - name: CONFIG_REPOSITORY_SERVICE_URL
          value: "http://scr-service.default.svc.cluster.local:30770"
        ports:
        - name: epts-port
          containerPort: 30740
        - name: jmx-port
          containerPort: 30741
        - name: debug-port
          containerPort: 30742
        livenessProbe:
          httpGet:
            path: /health
            port: epts-port
          initialDelaySeconds: 240
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: epts-port
          initialDelaySeconds: 1
          periodSeconds: 1
      volumes:
        - name: epts-conf-volume
          hostPath:
            path: /usr/lib/epts-service/conf
