---
apiVersion: v1
kind: Service
metadata:
  name: dcx-service
  labels:
    app: dcx-service
    tier: backend
spec:
  type: "LoadBalancer"
  ports:
  - port: 30780
    targetPort: 30780
    nodePort: 30780
    name: dcx
  selector:
    app: dcx-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dcx-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dcx-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: hub-deploy
      containers:
      - name: dcx-service
        image: hub.kaaiot.io/kaaiot/dcx/dcx-service:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /health
            port: dcx-port
          initialDelaySeconds: 150
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: dcx-port
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
          - mountPath: /usr/lib/dcx-service/conf
            name: dcx-conf-volume
        resources:
          requests:
            memory: 350Mi
          limits:
            memory: 1Gi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: NATS_HOST_PORT
          value: nats://nats-service.default.svc.cluster.local:4222
        - name: INSTANCE_NAME
          value: dcx
        - name: CONFIG_REPOSITORY_SERVICE_URL
          value: "http://scr-service.default.svc.cluster.local:30770"
        - name: DEPENDENCY_SERVICES_WAIT_TIMEOUT_SEC
          value: "60"
        - name: JAVA_OPTIONS
          value: -Xmx700m
        - name: APP_CONFIG_PATH
          value: /usr/lib/dcx-service/conf/app/app-config.yml
        - name: JMX_PORT
          value: "30781"
        - name: JMX_MONITOR_USER_PASSWORD
          value: monitor
        ports:
        - name: dcx-port
          containerPort: 30780
        - name: jmx-port
          containerPort: 30781
      volumes:
        - name: dcx-conf-volume
          hostPath:
            path: /usr/lib/dcx-service/conf
